name: Ubuntu Latest Build and Test with ASan on Qt 6.8+

on:
  push:
    branches:
      - master
      - dev
      - actions
  pull_request:
    branches:
      - master
      - dev
      - actions

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        qt_version: ['6.8.0']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup CMake and Ninja
      uses: lukka/get-cmake@latest

    - name: Setup C++ Compiler
      run: |
        sudo apt-get update &&
        sudo apt-get install -y g++-10 libglx-dev libgl1-mesa-dev &&
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 60 --slave /usr/bin/g++ g++ /usr/bin/g++-10

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ matrix.qt_version }}

    - name: Create Build Environment
      run: cmake -S . -B build -G Ninja -DENABLE_TESTING:BOOL=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-fsanitize=address"

    - name: Build Project
      run: cmake --build build

    - name: Run Tests
      env:
        ASAN_OPTIONS: detect_leaks=1
      run: cd build && ./tests/asyncfutureunittests
